In [1]:

# Import modules
from datetime import datetime, timedelta
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like #For solving import pandas_datareader issue
import numpy as np
import datetime
import csv
import requests
import pandas_datareader.data as web
import pandas_datareader as pdr
from pandas_datareader import data, wb
import datetime
from nsetools import Nse
from pprint import pprint
import pandas as pd
from datetime import date
#import yfinance as yf
from NSEDownload import stocks
from nsepython import *


today = date.today()

c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
currentDay = datetime.datetime.now().day
currentMonth = datetime.datetime.now().month
currentYear = datetime.datetime.now().year

# Input Start and End Date
start = datetime.datetime(2018,4,20)
end = datetime.datetime(currentYear,currentMonth,currentDay-1)

In [3]:
nse= Nse()
OptionLot = (nse.get_fno_lot_sizes())

In [4]:
print(OptionLot)
listOptions = OptionLot.keys()

{'FINNIFTY': 40, 'BANKNIFTY': 25, 'NIFTY': 75, 'AARTIIND': 425, 'ADANIENT': 2000, 'ADANIPORTS': 2500, 'AMARAJABAT': 1000, 'APOLLOTYRE': 5000, 'ASHOKLEY': 9000, 'APOLLOHOSP': 500, 'ASIANPAINT': 300, 'AUROPHARMA': 650, 'BAJAJ-AUTO': 250, 'BANKBARODA': 11700, 'BEL': 7600, 'AXISBANK': 1200, 'BERGEPAINT': 1100, 'BHEL': 21000, 'CADILAHC': 2200, 'CANBK': 5400, 'BAJFINANCE': 250, 'BALKRISIND': 400, 'CHOLAFIN': 2500, 'CIPLA': 1300, 'CONCOR': 1563, 'CUMMINSIND': 1200, 'DLF': 3300, 'BATAINDIA': 550, 'DRREDDY': 125, 'BHARTIARTL': 1851, 'FEDERALBNK': 10000, 'BPCL': 1800, 'HDFCAMC': 200, 'BRITANNIA': 200, 'HDFCBANK': 550, 'ACC': 500, 'IGL': 1375, 'ITC': 3200, 'JINDALSTEL': 5000, 'JSWSTEEL': 2700, 'L&TFH': 8924, 'LALPATHLAB': 250, 'COFORGE': 375, 'LICHSGFIN': 2000, 'LT': 575, 'LUPIN': 850, 'M&M': 1400, 'M&MFIN': 4000, 'MANAPPURAM': 6000, 'DIVISLAB': 200, 'ESCORTS': 550, 'MARUTI': 100, 'MFSL': 1300, 'NATIONALUM': 17000, 'NMDC': 6700, 'PAGEIND': 30, 'PEL': 550, 'EXIDEIND': 3600, 'PIDILITIND': 500, 'PVR': 407, 'SAIL': 19000, 'SBIN': 3000, 'SIEMENS': 550, 'GMRINFRA': 22500, 'SRF': 125, 'GODREJPROP': 650, 'SRTRANSFIN': 800, 'HCLTECH': 700, 'SUNPHARMA': 1400, 'TATACONSUM': 1350, 'TATAPOWER': 13500, 'TCS': 300, 'TECHM': 1200, 'HDFCLIFE': 1100, 'HEROMOTOCO': 300, 'HINDALCO': 4300, 'HINDPETRO': 2700, 'HINDUNILVR': 300, 'ICICIBANK': 1375, 'WIPRO': 3200, 'ICICIPRULI': 1500, 'IDFCFIRSTB': 19000, 'INDIGO': 500, 'INFY': 600, 'IOC': 6500, 'KOTAKBANK': 400, 'AMBUJACEM': 3000, 'MARICO': 2000, 'MCDOWELL-N': 1250, 'BHARATFORG': 1500, 'MGL': 600, 'MINDTREE': 800, 'MOTHERSUMI': 7000, 'MRF': 10, 'MUTHOOTFIN': 750, 'COALINDIA': 4200, 'NAUKRI': 250, 'NESTLEIND': 50, 'NTPC': 5700, 'ONGC': 7700, 'PETRONET': 3000, 'PFC': 6200, 'PNB': 16000, 'POWERGRID': 4000, 'DABUR': 1250, 'RAMCOCEM': 850, 'EICHERMOT': 350, 'RBLBANK': 2900, 'SBILIFE': 750, 'SUNTV': 1500, 'TATACHEM': 2000, 'GAIL': 6100, 'TATAMOTORS': 5700, 'GODREJCP': 1000, 'TATASTEEL': 1700, 'TITAN': 750, 'TORNTPOWER': 3000, 'GRASIM': 950, 'TVSMOTOR': 1400, 'ULTRACEMCO': 200, 'VOLTAS': 1000, 'BANDHANBNK': 1800, 'ZEEL': 3000, 'BIOCON': 2300, 'HDFC': 300, 'ICICIGI': 425, 'IDEA': 70000, 'INDUSTOWER': 2800, 'BAJAJFINSV': 125, 'BOSCHLTD': 50, 'COLPAL': 700, 'GLENMARK': 1150, 'HAVELLS': 1000, 'IBULHSGFIN': 3100, 'INDUSINDBK': 900, 'RECLTD': 6000, 'SHREECEM': 50, 'VEDL': 6200, 'TORNTPHARM': 250, 'UBL': 700, 'UPL': 1300, 'JUBLFOOD': 250, 'RELIANCE': 250}

In [6]:
df

,Symbol,Series,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,
Date,,,,,,,,,,,,,,,
02-Feb-2021,RELIANCE,EQ,1895.30,1914.25,1940.0,1854.95,1936.00,1925.80,1889.81,19138414,3.616805e+10,561567,7369471,38.51,
01-Feb-2021,RELIANCE,EQ,1841.95,1859.40,1905.0,1848.00,1898.15,1895.30,1874.03,15774504,2.956182e+10,370120,7864911,49.86,
29-Jan-2021,RELIANCE,EQ,1876.55,1894.30,1913.1,1830.00,1844.95,1841.95,1871.72,20173258,3.775861e+10,472678,9106845,45.14,
28-Jan-2021,RELIANCE,EQ,1895.00,1880.15,1923.3,1870.00,1876.35,1876.55,1895.32,15722291,2.979881e+10,446576,4697008,29.87,
27-Jan-2021,RELIANCE,EQ,1941.00,1925.00,1925.0,1888.00,1890.00,1895.00,1904.59,19553809,3.724198e+10,637355,9587173,49.03,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
07-Jan-2010,RELIANCE,EQ,1088.00,1088.00,1115.0,1078.00,1101.90,1106.05,1103.49,5988404,6.608116e+09,-,2522438,42.12,
06-Jan-2010,RELIANCE,EQ,1070.70,1079.90,1094.5,1070.65,1087.00,1088.00,1084.64,5415538,5.873928e+09,-,2539975,46.90,
05-Jan-2010,RELIANCE,EQ,1075.50,1149.90,1149.9,1065.40,1068.70,1070.70,1078.03,4890040,5.271634e+09,-,2861065,58.51,
04-Jan-2010,RELIANCE,EQ,1090.55,1091.10,1091.1,1021.85,1077.30,1075.50,1044.44,17520006,1.829863e+10,-,14348117,81.90,
31-Dec-2009,RELIANCE,EQ,1076.05,1084.00,1096.0,1081.35,1093.35,1090.55,1090.28,4009836,4.371858e+09,-,2150984,53.64,

In [7]:
import PYTopLosersTopGainersEquity as ab

Main-ed

In [8]:
TG = ab.getGainValue()

{'TG': 'Files/TopGainers2021-02-20.csv'}

In [9]:
TL = ab.getLostValue()

{'TL': 'Files/TopLosers2021-02-20.csv'}

In [10]:
data =pd.DataFrame(nse_events())

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.nseindia.com:443
DEBUG:urllib3.connectionpool:https://www.nseindia.com:443 "GET /api/event-calendar HTTP/1.1" 401 272
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): nseindia.com:80
DEBUG:urllib3.connectionpool:http://nseindia.com:80 "GET / HTTP/1.1" 301 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.nseindia.com:80
DEBUG:urllib3.connectionpool:http://www.nseindia.com:80 "GET / HTTP/1.1" 301 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.nseindia.com:443
DEBUG:urllib3.connectionpool:https://www.nseindia.com:443 "GET / HTTP/1.1" 200 39633
DEBUG:urllib3.connectionpool:https://www.nseindia.com:443 "GET /api/event-calendar HTTP/1.1" 200 2448

In [11]:
#print(TL)

       symbol series  openPrice  highPrice  lowPrice      ltp  previousPrice  \
0        ONGC     EQ     110.70     112.20    103.85   105.10         110.70
1   TATASTEEL     EQ     696.00     696.00    655.95   669.40         697.75
2  HEROMOTOCO     EQ    3522.85    3522.85   3370.00  3390.75        3522.85
3        SBIN     EQ     415.00     415.00    395.00   400.60         415.20
4  TATAMOTORS     EQ     321.95     321.95    301.40   312.45         323.85
5    AXISBANK     EQ     772.90     777.20    741.35   750.60         777.00
6   ICICIBANK     EQ     635.50     635.50    619.00   625.40         644.65
7  BAJAJ-AUTO     EQ    4106.00    4106.70   3977.20  4002.00        4115.45
8   EICHERMOT     EQ    2646.00    2647.90   2570.00  2582.00        2650.20
9    JSWSTEEL     EQ     408.10     408.40    390.95   398.30         407.65

  netPrice  tradedQuantity  turnoverInLakhs lastCorpAnnouncementDate  \
0    -5.06      48225988.0         52416.83              17-Feb-2021
1    -4.06      22392386.0        151251.61              06-Aug-2020
2    -3.75        995322.0         34123.82              15-Feb-2021
3    -3.52      66155518.0        267969.54              15-Jun-2018
4    -3.52      80274683.0        251508.61              18-Jul-2016
5    -3.40      15634787.0        118994.80              04-Jul-2019
6    -2.99      24055811.0        151056.06              22-Jul-2019
7    -2.76        762200.0         30614.83              03-Mar-2020
8    -2.57       1588781.0         41263.98              24-Aug-2020
9    -2.29       4527644.0         18129.59              06-Jul-2020

                                lastCorpAnnouncement
0               Interim Dividend - Rs 1.75 Per Share
1                         Dividend - Rs 10 Per Share
2  Interim Dividend - Rs 65 Per Share Special Div...
3  Annual General Meeting/ Change In Registrar An...
4                     Dividend - Re 0.20/- Per Share
5  Annual General Meeting/ Dividend - Re 1 Per Share
6   Annual General Meeting/Dividend - Re 1 Per Share
7                Interim Dividend - Rs 120 Per Share
8  Face Value Split (Sub-Division) - From Rs 10/-...
9                          Dividend - Rs 2 Per Share

In [12]:
#data['TopLoser'] = -1
#data['TopGainer'] = -1
data['HasOption'] = -1
TL['HasOption'] = -1
TG['HasOption'] = -1

In [13]:
for i, row in data.iterrows():
    if data.at[i,'symbol'] in listOptions:
        data.at[i,'HasOption'] = 1
    else:
        data.at[i,'HasOption'] = 0

In [14]:
#print(data)

        symbol                                       company  \
0       UNIPLY                     Uniply Industries Limited
1     DBREALTY                            D B Realty Limited
2    INDIAMART                   Indiamart Intermesh Limited
3    HUHTAMAKI                       Huhtamaki India Limited
4       SAFARI             Safari Industries (India) Limited
5       SANOFI                          Sanofi India Limited
6    HUHTAMAKI                       Huhtamaki India Limited
7       UNIPLY                     Uniply Industries Limited
8     VENUSREM                        Venus Remedies Limited
9   STOVEKRAFT                           Stove Kraft Limited
10     BIGBLOC                  Bigbloc Construction Limited
11    SPANDANA           Spandana Sphoorty Financial Limited
12  WEBELSOLAR                  Websol Energy System Limited
13  HINDMOTORS                      Hindustan Motors Limited
14    KRISHANA                     Krishana Phoschem Limited
15         KSB                                   Ksb Limited
16   MAWANASUG                         Mawana Sugars Limited
17        RAIN                       Rain Industries Limited
18   SOUTHBANK                 The South Indian Bank Limited
19   STEELCITY                 Steel City Securities Limited
20    VESUVIUS                        Vesuvius India Limited
21         HAL                 Hindustan Aeronautics Limited
22   JINDALSAW                            Jindal Saw Limited
23         KEI                        KEI Industries Limited
24   MODTHREAD                         Modern Thread Limited
25  POWERINDIA  ABB Power Products and Systems India Limited
26  POWERINDIA  ABB Power Products and Systems India Limited
27     SIMPLEX                      Simplex Projects Limited
28  LINDEINDIA                           Linde India Limited
29      JAGRAN                      Jagran Prakashan Limited
30      MARICO                                Marico Limited

                                     purpose  \
0                          Financial Results
1                               Fund Raising
2                     Other business matters
3                 Financial Results/Dividend
4                               Fund Raising
5                 Financial Results/Dividend
6                 Financial Results/Dividend
7                          Financial Results
8                     Other business matters
9   Financial Results/Other business matters
10                    Other business matters
11                              Fund Raising
12                    Other business matters
13                    Other business matters
14                    Other business matters
15                Financial Results/Dividend
16                    Other business matters
17                         Financial Results
18                              Fund Raising
19                                  Dividend
20                Financial Results/Dividend
21                                  Dividend
22                    Other business matters
23                                  Dividend
24                         Financial Results
25                Financial Results/Dividend
26                Financial Results/Dividend
27                         Financial Results
28                Financial Results/Dividend
29                                   Buyback
30                                  Dividend

                                              bm_desc         date  HasOption
0   Dear Madam/Sir,ￂﾠￂﾠSub: Intimation of Board Me...  21-Feb-2021          0
1                            To consider Fund Raising  22-Feb-2021          0
2   Fund Raise Committee Meeting is scheduled on 2...  22-Feb-2021          0
3   HUHTAMAKI : 24-Feb-2021 :  The Company has inf...  23-Feb-2021          0
4                            To consider Fund Raising  23-Feb-2021          0
5   To consider and approve the financial results ...  23-Feb-2021          0
6   To consider and approve the financial results ...  23-Feb-2021          0
7   To consider and approve the financial results ...  23-Feb-2021          0
8   To consider the allotment of 10,25,000 warrant...  23-Feb-2021          0
9   To consider and approve the financial results ...  23-Feb-2021          0
10  To consider other business mattersￂﾠ to discus...  24-Feb-2021          0
11                           To consider Fund Raising  24-Feb-2021          0
12  To consider o1. Proposal to raise resources by...  24-Feb-2021          0
13                 To consider other business matters  25-Feb-2021          0
14                 To consider other business matters  25-Feb-2021          0
15  To consider and approve the financial results ...  25-Feb-2021          0
16                 To consider other business matters  25-Feb-2021          0
17  To consider and approve the financial results ...  25-Feb-2021          0
18                           To consider Fund Raising  25-Feb-2021          0
19                               To consider dividend  25-Feb-2021          0
20  To consider and approve the financial results ...  25-Feb-2021          0
21                               To consider dividend  26-Feb-2021          0
22  To consider other business matters for conside...  26-Feb-2021          0
23                       To consider interim dividend  26-Feb-2021          0
24  To consider and approve the financial results ...  26-Feb-2021          0
25  To consider and approve the financial results ...  26-Feb-2021          0
26  POWERINDIA : 25-Feb-2021 : The Company has inf...  26-Feb-2021          0
27  To consider and approve the financial results ...  26-Feb-2021          0
28  This is to inform you that a meeting of the Bo...  01-Mar-2021          0
29              To consider buyback for equity shares  02-Mar-2021          0
30  Pursuant to Regulation 29 of the Securities an...  03-Mar-2021          1

In [15]:
for i, row in TL.iterrows():
    if TL.at[i,'symbol'] in listOptions:
        TL.at[i,'HasOption'] = 1
    else:
        TL.at[i,'HasOption'] = 0

In [16]:
for i, row in TG.iterrows():
    if TG.at[i,'symbol'] in listOptions:
        TG.at[i,'HasOption'] = 1
    else:
        TG.at[i,'HasOption'] = 0

In [17]:
symbols = []
symbols = TL.symbol.tolist()
symbols+= TG.symbol.tolist()
symbols+= data.symbol.tolist()

In [25]:
print("List Of Stocks to Analyse Today :- ")
print(symbols)

List Of Stocks to Analyse Today :-
['ONGC', 'TATASTEEL', 'HEROMOTOCO', 'SBIN', 'TATAMOTORS', 'AXISBANK', 'ICICIBANK', 'BAJAJ-AUTO', 'EICHERMOT', 'JSWSTEEL', 'UPL', 'DRREDDY', 'INDUSINDBK', 'HINDUNILVR', 'GAIL', 'NTPC', 'TCS', 'RELIANCE', 'NESTLEIND', 'BAJAJFINSV', 'UNIPLY', 'DBREALTY', 'INDIAMART', 'HUHTAMAKI', 'SAFARI', 'SANOFI', 'HUHTAMAKI', 'UNIPLY', 'VENUSREM', 'STOVEKRAFT', 'BIGBLOC', 'SPANDANA', 'WEBELSOLAR', 'HINDMOTORS', 'KRISHANA', 'KSB', 'MAWANASUG', 'RAIN', 'SOUTHBANK', 'STEELCITY', 'VESUVIUS', 'HAL', 'JINDALSAW', 'KEI', 'MODTHREAD', 'POWERINDIA', 'POWERINDIA', 'SIMPLEX', 'LINDEINDIA', 'JAGRAN', 'MARICO']

In [ ]:
'''
from datetime import date
from nsepy import get_history
stock_opt = get_history(symbol="HDFC",
 start=date(2019, 1, 15),
 end=date(2019, 2, 1),
 option_type="CE",
 strike_price=2000,
 expiry_date=date(2019, 2, 28))
stock_opt.head()
'''

In [ ]:
#df = stocks.get_data(stockSymbol="RELIANCE", start_date = '31-12-2009', end_date = '2-2-2021')
filenames=[]
for i in symbols:
    print("Generating for "+str(i))
    name=str(i) + str(today) + '.csv'
    filenames.append(name)
    newDF=stocks.get_data(stockSymbol=i, start_date = '31-12-2009', end_date = '20-2-2021')
    newDF.to_csv("Files\\HistoricalData\\"name)